<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2079697b-1b32-4b55-86f3-c58e1bc70008</testSuiteGuid>
   <testCaseLink>
      <guid>1650ca15-5937-4da0-b79c-406d78f9b063</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login - Blank</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b2647fd-0b64-463a-9108-45e0d87fadcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf19f06e-0732-47af-89f1-8af76d4931e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>26ebe0a8-ddd7-4657-a41b-55b17d617336</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login - Incorrect Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>864d801b-8889-4458-aeb8-15de14e46bb9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ead95610-7b25-4f9a-90e8-f1965bd06e7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0e1f0ad-2edf-4d7f-a546-f22f74566060</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login - Incorrect Username</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0e57162-0b66-48b0-ac09-9a1fbf966964</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90aeb65c-51ba-4e06-be4c-47ef50d0c47b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1985d0b0-4a27-4251-a6dd-da603bd85444</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login - Incorrect Username and Password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a27fd65-3cd4-45cf-bca3-dabb9b4d0c24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fb6a9b1-270f-4509-a411-cd0571c88468</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1048405d-357d-4796-9b28-5d135c162c1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login - Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd547ac9-9d3c-4401-ac0d-057c56e34d64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>958013b4-f21b-4b58-b4bd-414c686a13d3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
