<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Image - T-Shirt</name>
   <tag></tag>
   <elementGuidId>4cc7c6a4-c5df-401b-ba14-00712ffe519e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sticky_bottom_anchor']/ul/li[3]/div/div/div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2c143ae8-eb8a-488c-bcc4-008f3329c03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>330</value>
      <webElementGuid>156edd66-e362-4368-b442-d6054018dfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>413</value>
      <webElementGuid>7aa56c12-161c-430d-a28f-d2a188c74b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-330x413.jpg</value>
      <webElementGuid>05bd5d3d-51b2-4e5e-ac18-e1c7812ec47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>1b239114-4e02-477b-a422-5b2fa6bce590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>d8e965c9-3513-47c2-bfda-58432cc7413f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-330x413.jpg 330w, https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002.jpg 333w</value>
      <webElementGuid>dd8ddd91-fba7-4dae-80e2-27b611d3808d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 330px) 100vw, 330px</value>
      <webElementGuid>b44b6337-0c06-49fb-a638-7360b32d3154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky_bottom_anchor&quot;)/ul[@class=&quot;products columns-3 js_animated&quot;]/li[@class=&quot;product type-product post-237 status-publish instock product_cat-uncategorized has-post-thumbnail shipping-taxable purchasable product-type-simple visible animation_ready animated&quot;]/div[@class=&quot;main-container&quot;]/div[@class=&quot;product_image_wrapper&quot;]/div[@class=&quot;product_image&quot;]/a[1]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>a6e2aba2-c4b0-4cbb-8a7a-68333e9f2a89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sticky_bottom_anchor']/ul/li[3]/div/div/div[2]/a/img</value>
      <webElementGuid>2f0f77af-cf6a-4d65-b957-89619f6fd509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-330x413.jpg')]</value>
      <webElementGuid>03ee7e05-e762-4a1d-b625-60c22208baea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div[2]/a/img</value>
      <webElementGuid>cfd5172f-c39d-4c0c-9c5b-8bdcc596a2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-330x413.jpg']</value>
      <webElementGuid>febe171d-7c59-4a28-8b55-2d50f8e9eee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
