<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Image - Polo</name>
   <tag></tag>
   <elementGuidId>3076e979-be97-456b-a8c4-638b6c6ced56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.wp-post-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sticky_bottom_anchor']/div/figure/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>064c2f49-a2ed-4b68-9b78-2096618a03a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>333</value>
      <webElementGuid>3d802579-068d-4216-9e83-9ca8b13bbea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>416</value>
      <webElementGuid>fcdd44b0-9604-42ce-a7ed-28e3af55c66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002.jpg</value>
      <webElementGuid>64e05ae7-309a-4dfa-b36b-52422ddcb2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-post-image</value>
      <webElementGuid>74f5fe2a-ddc5-44ab-a56f-fcffad560d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>9243ca36-933c-41e4-8fd0-2840b4d39fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>IMG-20220606-WA0002</value>
      <webElementGuid>3ac075bd-a8a0-4878-8382-e429d8fadc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002.jpg</value>
      <webElementGuid>9c517c35-026d-40a8-8632-6ad083c9d37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-large_image</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002.jpg</value>
      <webElementGuid>adabe3ee-80c8-41cb-9a2e-715e0f6ce72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-large_image_width</name>
      <type>Main</type>
      <value>333</value>
      <webElementGuid>e33cd3ec-717c-42ef-a52a-1007318f65f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-large_image_height</name>
      <type>Main</type>
      <value>416</value>
      <webElementGuid>ebeb6572-be79-4b43-81b1-4e9b13f03e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002.jpg 333w, https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002-330x413.jpg 330w</value>
      <webElementGuid>e20f0892-103d-4677-b128-646c03ba9fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 333px) 100vw, 333px</value>
      <webElementGuid>f06a5581-c513-4ecf-9b92-fabafaeb1116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky_bottom_anchor&quot;)/div[@class=&quot;woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-6 images&quot;]/figure[@class=&quot;woocommerce-product-gallery__wrapper&quot;]/div[@class=&quot;woocommerce-product-gallery__image&quot;]/a[1]/img[@class=&quot;wp-post-image&quot;]</value>
      <webElementGuid>7b97397e-db7f-4f0c-9eee-b6828343138e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sticky_bottom_anchor']/div/figure/div/a/img</value>
      <webElementGuid>ed658c59-96a7-4b78-aa87-c6dac9b93a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='IMG-20220606-WA0002']</value>
      <webElementGuid>7e1789e7-a0ed-4434-8322-91f66a267aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/div/a/img</value>
      <webElementGuid>5f505b43-a800-4473-b9fc-1fe8c20a2f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://kotakoki.wijaysali.my.id/wp-content/uploads/2022/06/IMG-20220606-WA0002.jpg' and @title = 'IMG-20220606-WA0002']</value>
      <webElementGuid>7ed22ff8-3360-4180-9b5a-09f17e366c89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
