<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox - Keep Signed In</name>
   <tag></tag>
   <elementGuidId>a8226fc1-40d5-4428-9eb3-d3ad5a3752d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-313']/div/div/div/form/div[2]/div/div/label/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.um-icon-android-checkbox-outline-blank</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>97a50ee1-0e09-4879-83aa-5958f095fc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-icon-android-checkbox-outline-blank</value>
      <webElementGuid>612e483f-784a-4657-bd13-97ece7dbb736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-313&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;um um-login um-298 uimob500&quot;]/div[@class=&quot;um-form&quot;]/form[1]/div[@class=&quot;um-col-alt&quot;]/div[@class=&quot;um-field um-field-c&quot;]/div[@class=&quot;um-field-area&quot;]/label[@class=&quot;um-field-checkbox&quot;]/span[@class=&quot;um-field-checkbox-state&quot;]/i[@class=&quot;um-icon-android-checkbox-outline-blank&quot;]</value>
      <webElementGuid>1811f250-8ae0-4575-a8ea-4e7b405b04cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-313']/div/div/div/form/div[2]/div/div/label/span/i</value>
      <webElementGuid>9f7df252-5466-44f7-8cb4-743d697a13d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>9d390d6f-4ac3-41e1-aec6-c9fae6a0877f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
