<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown - Category</name>
   <tag></tag>
   <elementGuidId>4dfea7bd-42ec-4a01-9620-d886f3c6657e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='header_search_category']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header_search_category</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e00bef07-523c-48a0-b8e9-227fb4a2c9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_category</value>
      <webElementGuid>d3bb1f86-c887-4107-a143-8dc3ef3e6fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header_search_category</value>
      <webElementGuid>c6447367-538b-4b83-b924-12157ad22986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header_search_select</value>
      <webElementGuid>73d73bb8-4cec-4143-a617-912b889045ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Select CategoryUncategorizedCocoqua ココナッツDu-reamyドリアンHOME PAGEKOTAKOKI SETPIPILTIN COCOAREADY TO EATSEAFOODSPICESSTARTER SETスパイスブレンドテンペ新しいレシピセット</value>
      <webElementGuid>5c827044-7623-473f-90f7-08935f691334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_search_category&quot;)</value>
      <webElementGuid>f123f979-6677-4409-bccf-59d4d4e8e568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4c16e787-488b-455c-bcdd-33f597767ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_category</value>
      <webElementGuid>90307cca-e7f4-43af-a3ef-7179108ecb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header_search_category</value>
      <webElementGuid>850f5ac4-97ea-4b54-b3b8-f20b1913a0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header_search_select</value>
      <webElementGuid>d542dca1-a9c8-41b0-ad94-14813e659cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Select CategoryUncategorizedCocoqua ココナッツDu-reamyドリアンHOME PAGEKOTAKOKI SETPIPILTIN COCOAREADY TO EATSEAFOODSPICESSTARTER SETスパイスブレンドテンペ新しいレシピセット</value>
      <webElementGuid>de426ff1-a75f-436b-85af-76a87460ea9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_search_category&quot;)</value>
      <webElementGuid>73761228-bad7-4f76-8f91-92823c99e1a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='header_search_category']</value>
      <webElementGuid>a2262258-92b4-415c-a30c-29e1b9f09b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Featured products'])[1]/preceding::select[1]</value>
      <webElementGuid>09812bde-1415-4dbe-8451-ed41c0a7b5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cap'])[1]/preceding::select[1]</value>
      <webElementGuid>32570e84-1b93-41f1-86c5-7e0cbc356805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>05c661b9-bc04-4d9f-9f8f-b2db8b2774ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'search_category' and @id = 'header_search_category' and (text() = '
										Select CategoryUncategorizedCocoqua ココナッツDu-reamyドリアンHOME PAGEKOTAKOKI SETPIPILTIN COCOAREADY TO EATSEAFOODSPICESSTARTER SETスパイスブレンドテンペ新しいレシピセット' or . = '
										Select CategoryUncategorizedCocoqua ココナッツDu-reamyドリアンHOME PAGEKOTAKOKI SETPIPILTIN COCOAREADY TO EATSEAFOODSPICESSTARTER SETスパイスブレンドテンペ新しいレシピセット')]</value>
      <webElementGuid>a981d6a0-2458-4d7e-8038-c3378282f1b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
